from . import booking_info
from . import account_info
from . import accounts
from . import admin_login_his
from . import admin_privacy_his 
from . import api_log
from . import bookg_confirm_his
from . import persons
from . import visit_customer
from . import payment_infos
from . import sales_infos
from . import day_sum_payments
from . import day_sum_greenfees
from . import bookg_info_his
from . import members
from . import time_table_has_bookg_infos
from . import time_table