from odoo import models, fields

class AccountDetails(models.Model):
    _name = "account.details"
    _description = "Account Details"

    account_id = fields.Char(string="Account ID", required=True)
    account_code = fields.Char(string="Account Code")
    bsu_name = fields.Char(string="BSU Name")
    ceo_name = fields.Char(string="CEO Name")
    manager = fields.Char(string="Manager")
    cc_bsu_name = fields.Char(string="CC BSU Name")
    post_no = fields.Char(string="Post No")
    addr = fields.Char(string="Address")
    addr_extra = fields.Char(string="Address Extra")
    tel = fields.Char(string="Telephone")
    fax = fields.Char(string="Fax")
    booking_tel = fields.Char(string="Booking Tel")
    front_tel = fields.Char(string="Front Tel")
    game_tel = fields.Char(string="Game Tel")
    room_tel = fields.Char(string="Room Tel")
    business_no = fields.Char(string="Business No")
    corp_no = fields.Char(string="Corporate No")
    business_status = fields.Char(string="Business Status")
    business_event = fields.Char(string="Business Event")
    condo_yn = fields.Char(string="Condo Active?")
    home_tax = fields.Char(string="Home Tax")
    tax_area = fields.Char(string="Tax Area")
    tax_code = fields.Char(string="Tax Code")
    lang_scd = fields.Char(string="Language Code")
    bsu_name_abbr = fields.Char(string="BSU Name Abbreviation")
    group_yn = fields.Char(string="Group Active?")
    use_yn = fields.Char(string="Use Active?")
    created_id = fields.Char(string="Created By")
    created_at = fields.Datetime(string="Created At")
    updated_id = fields.Char(string="Updated By")
    updated_at = fields.Datetime(string="Updated At")
    deleted_id = fields.Char(string="Deleted By")
    deleted_at = fields.Datetime(string="Deleted At")
    sort_order = fields.Float(string="Sort Order")
    co_area = fields.Char(string="Company Area")
